### ISSUE TITLE
example.tscn is missing

### ISSUE THREAD

**Issue by IanMancuso** [Sinowa-Programming/Godot-Sweepline-Volornoi#5]
example.tscn is referenced in the "Operation" section of the readme, though clicking the link gives me a 404 error. example.tscn does not appear to be present in the file structure.

**Comment by Sinowa-Programming** [comment]
Sorry, I forgot to upload the example. It should be present now. Thank you for bringing this to my attention!

**Comment by IanMancuso** [comment]
Thank you very much!
